### ISSUE TITLE
Ubuntu Overlay Scrollbar color in GTK3 Apps

### ISSUE THREAD

**Issue by Sadi58** [killhellokitty/delorean#5]
I think it would be better to choose a lighter color for Ubuntu's Overlay Scrollbar -- even up and down arrows can hardly be seen now (in DeLorean-3.16 also), as shown in the screenshot below:
![delorean - overlay scrollbar](https://cloud.githubusercontent.com/assets/6375934/7631861/41bcf472-fa50-11e4-9d99-e3b7f9d1ec9d.png)
The Up and Down Arrows seen in the screenshot are actually invisible. They are visible here because the overlay becomes lighter and lighter when you hold the mouse over it and that's what I had to do to take the screenshot.

Additionally, it seems this issue affects only GTK3 apps, and not GTK2.

**Comment by Sadi58** [comment]
The Up and Down Arrows seen in the screenshot are actually invisible. They are visible here because the overlay becomes lighter and lighter when you hold the mouse over it and that's what I had to do to take the screenshot.
I think this is the last issue remaining - probably to be fixed in `ubuntu_styles.css`

**Comment by killhellokitty** [comment]
I changed all the overlay scrollbar colors to blue and they had no effect.
I don't believe Ubuntu has the theming for them working properly.

**Comment by Sadi58** [comment]
As Ubuntu has abandoned its own overlay scrollbars in favor of Gnome's starting from 15.10, I think we can close this issue now ;-)
