### ISSUE TITLE
Synaptic toolbar background

### ISSUE THREAD

**Issue by Sadi58** [killhellokitty/delorean#6]
I've heard somewhere that a little extra tweak is required for Synaptic package manager to display a uniform toolbar background (as in DeLorean-3.16). Otherwise it becomes patchy as shown in the screenshot below:
![delorean3 14-synaptic](https://cloud.githubusercontent.com/assets/6375934/7631911/bce58704-fa50-11e4-860c-9d35bf825c30.png)

**Comment by killhellokitty** [comment]
Hi Sadi,
version 23 of DeLorean-3,14 has the fixes for the synaptic toolbar and the
Nautilus secondary labels added, plus I removed the background placement
that was giving error messages.
Cheers!

**Comment by Sadi58** [comment]
That's great! Thank you!
